# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "air"
remote_theme             : "mmistakes/minimal-mistakes"

# Site Settings
locale                   : "en-US"
title                    : "The Evolving Admin"
title_separator          : "-"
github			 : [metadata]
name                     : "Damien Solodow"
description              : "My technical/IT related musings and learning experiences"
url                      : "http://theevolvingadmin.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "dsolodow/dsolodow-github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "theevolvingadmin"
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : false
future			 : false

# SEO Related
google_site_verification :
bing_site_verification   :

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-114028220-1"

# Site Author
author:
  name             : "Damien Solodow"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Long time Windows sysadmin, lifelong geek. Married crazy cat guy."
  location         : "Central Indiana"
  email            : "bookwyrm79@gmail.com"
  uri              : "http://theevolvingadmin.com"
  home             : # null (default), "absolute or relative url to link to author home"
  github           : "dsolodow"
  linkedin         : "damien-solodow-56155914"
  stackoverflow    : "9352249/damien-solodow"
  twitter          : "dsolodow"

# Social Sharing
og_image               : /assets/images/bio-photo.jpg

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Indiana/Indianapolis

include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .markdownlint.json
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Gemfile
  - node_modules
  - package.json
  - README
  - _drafts/template.md
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-mentions
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-mentions
# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: false
      permalink: /:year/:month/:day/:title
