# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "air"
remote_theme             : "mmistakes/minimal-mistakes"

# Site Settings
locale                   : "en-US"
title                    : "The Evolving Admin"
title_separator          : "-"
github			 : [metadata]
name                     : "Damien Solodow"
description              : "My technical/IT related musings and learning experiences"
url                      : "https://dsolodow.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "dsolodow/dsolodow-github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "theevolvingadmin"
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : false

# SEO Related
google_site_verification :
bing_site_verification   :

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-114028220-1"

# Site Author
author:
  name             : "Damien Solodow"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "TBD"
  location         : "Central Indiana"
  email            : "bookwyrm79@gmail.com"
  uri              : "https://dsolodow.github.io"
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        : "dsolodow"
  codepen          :
  dribbble         :
  facebook         :
  github           : "dsolodow"
  gitlab           : "dsolodow"
  google_plus      :
  keybase          :
  instagram        :
  linkedin         : "damien-solodow-56155914"
  stackoverflow    : "9352249/damien-solodow"
  twitter          : "dsolodow"
  youtube          : 

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Indiana/Indianapolis

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: false 

